In [14]:
import numpy as np

In [38]:
my_list = [1, 2, 3]

In [39]:
my_matrix =[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [40]:
arr = np.array(my_list)

In [41]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# arange

In [15]:
# listのrangeと同じ

In [8]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# linspace

In [ ]:
# 0から5を10分割

In [44]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

# eye

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# rand

In [20]:
np.random.rand(2, 5)

array([[0.95198405, 0.82527889, 0.41016987, 0.8400366 , 0.07024894],
       [0.73708172, 0.27218394, 0.6218377 , 0.34441014, 0.33379269]])

# randint

In [ ]:
# 1から100の間でrandamな数字を10作る

In [19]:
np.random.randint(1, 100, 10)

array([51, 93, 19, 37, 99, 47, 27, 32, 40, 33])

# reshape

In [21]:
arr = np.arange(25)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# max, min

In [8]:
ranarr = np.random.randint(0, 50, 10)

In [9]:
ranarr

array([20, 38, 30, 15, 22,  8, 21, 15, 42,  8])

In [10]:
ranarr.max()

42

In [11]:
ranarr.min()

8

In [12]:
# maxの位置
ranarr.argmax()

8

In [13]:
# minの位置
ranarr.argmin()

5

# dtype

In [19]:
arr.dtype

dtype('int32')