In [3]:
import numpy as np

In [4]:
arr = np.arange(0, 11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# slicing

In [6]:
arr[8]

8

In [7]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[:5]

array([0, 1, 2, 3, 4])

In [10]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [33]:
# 全配列に同じあたりを展開する
arr[0:5] = 100

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

# copy

In [ ]:
# コピーではなく、参照渡しになっている

In [25]:
arr = np.arange(0, 11)

In [26]:
copy_arr = arr

In [27]:
arr[0] = 99

In [32]:
# 参照渡しになっている
copy_arr

array([99, 98,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# コピーしないとダメ
true_copy_arr = arr.copy()

In [30]:
arr[1] = 98

In [31]:
true_copy_arr

array([99,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# matrix

In [36]:
arr_2d = np.array(
    [
        [5,10,15]
       ,[20,25,30]
       ,[35,40,45]
    ])

In [38]:
arr_2d[1][2]

30

In [40]:
# これもできるし、こっちがお勧め
arr_2d[1, 2]

30

In [44]:
# row:全部、col:1から最後まで
arr_2d[:,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [46]:
# row:1から最後まで、col:全部
arr_2d[1:,:]

array([[20, 25, 30],
       [35, 40, 45]])

# conditional selection

In [48]:
arr = np.arange(1, 11)

In [49]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
bool_arr = arr > 5

In [53]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [54]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [57]:
# 1stepでやると
arr[arr > 5]

array([ 6,  7,  8,  9, 10])